routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');


Route::get('/cart/checkout', 'CartController@checkout')->name('cart.checkout');
Route::post('/cart/authenticate', 'CartController@authenticate')->name('cart.authenticate');
Route::post('/cart/register', 'CartController@register')->name('cart.register');



Route::middleware(['auth'])->group(function () {
    Route::post('/cart/pay', 'CartController@pay')->name('cart.pay');
    Route::post('/cart/makeOrder', 'CartController@makeOrder')->name('cart.makeOrder');
    Route::get('/cart/order/{id}', 'CartController@order')->name('cart.order');
    Route::get('/cart/orders', 'CartController@orders')->name('cart.orders');
    Route::get('/logout', 'HomeController@logout')->name('logout');

    Route::get('/admin/orders', 'AdminController@orders')->name('admin.orders');
    Route::get('/admin/order/{id}', 'AdminController@order')->name('admin.order');
});
Route::resource('cart', 'CartController');
Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Exception;


/**
 * @property string password
 * @property string email
 * @property boolean is_active
 * @property int id
 * @property mixed passwordSecurities
 * @property mixed|string first_name
 * @property mixed|string last_name
 * @property mixed|string telephone
 * @property mixed|string address
 */
class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'password','email',
    ];

    public function getFullNameAttribute()
    {
        $fullName = $this->middle_name != '' ?
            "{$this->first_name} {$this->middle_name} {$this->last_name}"
            : "{$this->first_name} {$this->last_name}";

        if ($this->salutation) {
            $salutationCode = $this->salutation->code;
            $fullName = "$salutationCode $fullName";
        }

        return $fullName;
    }

    public function getNameAttribute()
    {
        return $this->email;
    }
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">
<head>
    @include('layouts.head')
</head>
<body>
<div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img
            src="images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820"
            alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a>
</div>
<div class="preloader">
    <div class="cssload-container">
        <div class="cssload-speeding-wheel"></div>
    </div>
</div>
<!-- Page-->
<div class="page">
    @include('layouts.header', ['loc' => 'home'])
    @yield('content')
    @include('layouts.footer')
</div>
<!-- Javascript-->
<script src="js/core.min.js"></script>
<script src="js/script.js"></script>
<!-- coded by barber-->
</body>
</html>

resources/views/layouts/auth-app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ config('app.name', '') }} - @yield('title')</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
    <!--===============================================================================================-->

    <link rel="stylesheet" type="text/css" href="{{ asset('css/fonts.css') }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/icon-font.min.css') }}">
    <!--===============================================================================================-->
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/auth/util.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/auth/main.css') }}">
    <!--===============================================================================================-->
</head>
<body>

<div class="limiter">
    <div class="container-login100">
        @yield('content')
    </div>
</div>

</body>
</html>

resources/views/layouts/cart-app.blade.php
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">
<head>
    @include('layouts.head')
</head>
<body>
<div class="ie-panel">
    <a href="http://windows.microsoft.com/en-US/internet-explorer/">
        <img src="{{ asset("images/ie8-panel/warning_bar_0000_us.jpg") }}" height="42" width="820"
             alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today.">
    </a>
</div>
<div class="preloader">
    <div class="cssload-container">
        <div class="cssload-speeding-wheel"></div>
    </div>
</div>
<!-- Page-->
<div class="page">
    @include('layouts.header', ['loc' => 'cart'])
    @yield('content')
    @include('layouts.footer')
</div>
<!-- Javascript-->
<script src="{{ asset('js/core.min.js') }}"></script>
<script src="{{ asset('js/script.js') }}"></script>
<script src="{{ asset('js/toastr.min.js') }}"></script>
<script type="text/javascript">
    $(function () {

        @if (session('info'))
        toastr.info('{{session('info')}}');
        @endif

        @if (session('warning'))
        toastr.warning('{{session('warning')}}');
        @endif

        @if (session('success'))
        toastr.success('{{session('success')}}');
        @endif

        @if (session('error'))
        toastr.error('{{session('error')}}');
        @endif
    });
</script>
@yield('js')
<!-- coded by barber-->
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="novi-background bg-cover footer-corporate bg-gray-darker">
    <div class="container">
        <div class="footer-corporate__inner">
            <p class="rights"><span>King of Kings Mining Company Limited</span><span>&nbsp;</span><span
                    class="copyright-year"></span>. All Rights Reserved</p>
            <ul class="list-inline-xxs">
                <li><a class="icon novi-icon icon-xxs icon-gray-darker fa fa-facebook" href="#"></a></li>
                <li><a class="icon novi-icon icon-xxs icon-gray-darker fa fa-twitter" href="#"></a></li>
                <li><a class="icon novi-icon icon-xxs icon-gray-darker fa fa-google-plus" href="#"></a></li>
                <li><a class="icon novi-icon icon-xxs icon-gray-darker fa fa-vimeo" href="#"></a></li>
                <li><a class="icon novi-icon icon-xxs icon-gray-darker fa fa-youtube" href="#"></a></li>
                <li><a class="icon novi-icon icon-xxs icon-gray-darker fa fa-pinterest" href="#"></a></li>
            </ul>
        </div>
    </div>
</footer>

resources/views/layouts/head.blade.php
<!-- Site Title-->
<title>{{ config('app.name', '') }} - @yield('title')</title>
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="format-detection" content="telephone=no">
<meta name="viewport"
      content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta charset="utf-8">
<link rel="icon" href="images/favicon.ico" type="image/x-icon">
<!-- Stylesheets-->
<link rel="stylesheet" type="text/css"
      href="//fonts.googleapis.com/css?family=Lato:300,300italic%7CMontserrat:400,700">
<link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet" type="text/css">
<link href="{{ mix('css/compiled/app.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('css/fonts.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('css/toastr.min.css') }}" rel="stylesheet" type="text/css">
<style>.ie-panel {
        display: none;
        background: #212121;
        padding: 10px 0;
        box-shadow: 3px 3px 5px 0 rgba(0, 0, 0, .3);
        clear: both;
        text-align: center;
        position: relative;
        z-index: 1;
    }

    html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {
        display: block;
    }
</style>

resources/views/layouts/header.blade.php
<header class="page-header {{ $loc }}">
    <!-- RD Navbar-->
    <div class="rd-navbar-wrap">
        <nav class="rd-navbar {{ $loc == 'home' ? 'rd-navbar_transparent' : '' }} rd-navbar_boxed"
             data-layout="rd-navbar-fixed"
             data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed"
             data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static"
             data-xl-device-layout="rd-navbar-static" data-xxl-layout="rd-navbar-static"
             data-xxl-device-layout="rd-navbar-static" data-lg-stick-up="true" data-xl-stick-up="true"
             data-xxl-stick-up="true" data-lg-stick-up-offset="50px" data-xl-stick-up-offset="50px"
             data-xxl-stick-up-offset="50px" data-body-class="rd-navbar-absolute">
            <!-- RD Navbar Top Panel-->
            <div class="rd-navbar-top-panel">
                <div class="rd-navbar-top-panel__main">
                    <div class="rd-navbar-top-panel__toggle rd-navbar-fixed__element-1 rd-navbar-static--hidden"
                         data-rd-navbar-toggle=".rd-navbar-top-panel__main"><span></span></div>
                    <div class="rd-navbar-top-panel__content">
                        <div class="rd-navbar-top-panel__left">
                            <ul class="rd-navbar-items-list">
                                <li>
                                    <div class="unit flex-row align-items-center unit-spacing-xs">
                                        <div class="unit__left"><span
                                                class="icon novi-icon icon-sm icon-primary linearicons-map-marker"></span>
                                        </div>
                                        <div class="unit__body">
                                            <p><a href="#">Address: Plot 12 Luthuri Avenue. P.O.Box 2000 Kampala.</a>
                                            </p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="unit flex-row align-items-center unit-spacing-xs">
                                        <div class="unit__left"><span
                                                class="icon novi-icon icon-sm icon-primary linearicons-telephone"></span>
                                        </div>
                                        <div class="unit__body">
                                            <ul class="list-semicolon">
                                                <li><a href="tel:#">(+256) 772-722-132</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="rd-navbar-top-panel__right">
                            <ul class="list-inline-xxs">
                                @auth
                                    <li>
                                        {{-- TODO add user management --}}
                                        <a class="icon novi-icon icon-xxs icon-gray-darker" href="#">
                                            {{ auth()->user()->full_name }}
                                        </a>
                                    </li>
                                    @can('admin')
                                        <li><a class="icon-gray-darker" href="{{ route('admin.orders') }}">Orders</a></li>
                                    @endcan
                                @endauth
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="rd-navbar-inner rd-navbar-search-wrap">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel rd-navbar-search-lg_collapsable">
                    <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                    <!-- RD Navbar Brand-->
                    <div class="rd-navbar-brand">
                        <a class="brand-name" href="{{ route('home') }}">
                            <img src="{{ asset('images/logo.png') }}" alt="" width="304" height="39"/>
                        </a>
                    </div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap rd-navbar-search_not-collapsable">
                    <div class="rd-navbar-search_collapsable">
                        <ul class="rd-navbar-nav">
                            @if($loc == 'home')
                                <li><a href="#home">Home</a></li>
                                <li><a href="#about">About</a></li>
                                <li><a href="#products">Products</a></li>
                                <li><a href="#contacts">Contacts</a></li>
                            @else
                                <li><a href="{{ route('home') }}">Home</a></li>
                            @endif

                            @auth
                                <li><a href="{{ route('cart.orders') }}">My orders</a></li>
                                <li><a href="{{ route('logout') }}">Logout</a></li>
                            @endauth
                            @guest
                                <li><a href="{{ route('login') }}">Login</a></li>
                            @endguest
                            <li class="shopping_cart">
                                <a href="{{ route('cart.index') }}" class="shopping_cart_icon">
                                    <i class="fas fa-shopping-cart fa-2x">
                                            <span class="count">
                                                @if(session()->has('cart_count'))
                                                    {{session('cart_count')}}
                                                @else
                                                    0
                                                @endif
                                            </span>
                                    </i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</header>